In [3]:
# feature extractoring and preprocessing data
import librosa
import time
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
from PIL import Image
import pathlib 
import IPython
import csv

# Preprocessing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import confusion_matrix



#Import Tensorflow
import tensorflow as tf
#Keras
from tensorflow import keras

import warnings
warnings.filterwarnings('ignore')

os.chdir("/Users/shreevathsapk/Desktop/Miniprj")

In [30]:
header = 'filename chroma_stft spectral_centroid spectral_bandwidth rolloff zero_crossing_rate'
for i in range(1, 21):
    header += f' mfcc{i}'
header += ' label'
header = header.split()


file = open('data.csv', 'w', newline='')
with file:
    writer = csv.writer(file)
    writer.writerow(header)
#instruments = 'piano strings flute harmonium sarod shankha sitar veena violin'.split()
instruments = 'Bass_Acoustic Bass_electronic Bass_Synthetic Flute Guitar_Acoustic Guitar_electronic keyboard_acoustic keyboard_elec keyboard_synth mallet_acoustic organ_electronic reed_acoustic string_acoustic vocal_synth'.split()

for g in instruments:
    print(g);
    for filename in os.listdir(f'/Users/shreevathsapk/Desktop/Miniprj/instrumentdata/{g}'):
        if filename.endswith(('.mp3', '.wav', '.flac','.ogg')):
            #print(filename) #
            songname = f'/Users/shreevathsapk/Desktop/Miniprj/instrumentdata/{g}/{filename}'
            y, sr = librosa.load(songname, mono=True, duration=30)
            chroma_stft = librosa.feature.chroma_stft(y=y, sr=sr)
            spec_cent = librosa.feature.spectral_centroid(y=y, sr=sr)
            spec_bw = librosa.feature.spectral_bandwidth(y=y, sr=sr)
            rolloff = librosa.feature.spectral_rolloff(y=y, sr=sr)
            zcr = librosa.feature.zero_crossing_rate(y)
            mfcc = librosa.feature.mfcc(y=y, sr=sr)
            to_append = f'{filename} #{np.mean(chroma_stft)} #{np.mean(spec_cent)} #{np.mean(spec_bw)} #{np.mean(rolloff)} #{np.mean(zcr)}'    
            for e in mfcc:
                to_append += f' #{np.mean(e)}'
            to_append += f' #{g}'
            file = open('data.csv', 'a', newline='')
            with file:
                writer = csv.writer(file)
                writer.writerow(to_append.split("#"))
                

Bass_Acoustic
Bass_electronic
Bass_Synthetic
Flute
Guitar_Acoustic
Guitar_electronic
keyboard_acoustic
keyboard_elec
keyboard_synth
mallet_acoustic
organ_electronic
reed_acoustic
string_acoustic
vocal_synth


In [4]:
data = pd.read_csv('data.csv')

export_csv = data.to_csv (r'/Users/shreevathsapk/Desktop/Miniprj/pandaresult.csv', index = None, header=True)

In [32]:
data

filename  chroma_stft  spectral_centroid  \
0      brass_acoustic_015-063-075.wav      0.116223         772.089791   
1      brass_acoustic_059-046-025.wav      0.222872         706.261907   
2      brass_acoustic_016-089-050.wav      0.153270        4293.149869   
3      brass_acoustic_046-086-025.wav      0.780810        3257.143238   
4      brass_acoustic_046-096-025.wav      0.780810        3257.143238   
...                                ...          ...                ...   
4091  vocal_synthetic_003-108-075.wav      0.203392        3651.378173   
4092  vocal_synthetic_003-084-075.wav      0.131949        1867.576598   
4093  vocal_synthetic_003-060-100.wav      0.262238        2657.255749   
4094   vocal_acoustic_000-050-050.wav      0.181503         735.430912   
4095   vocal_acoustic_000-059-127.wav      0.122303        1315.763827   

      spectral_bandwidth      rolloff  zero_crossing_rate       mfcc1  \
0             669.901684  1272.699433            0.044925 -469.896637   
1             591.486416  1106.719512            0.061295 -392.835815   
2            1397.840548  5644.873188            0.397055 -481.355225   
3            1859.838776  5358.157966            0.295142  -31.477379   
4            1859.838776  5358.157966            0.295142  -31.477379   
...                  ...          ...                 ...         ...   
4091         2086.068616  6325.160597            0.315957 -171.960876   
4092         1543.836180  3447.739653            0.139829 -398.415009   
4093         1891.021536  4952.325545            0.183010 -193.338959   
4094          992.885352  1796.093186            0.023502 -303.862122   
4095         1154.395130  2451.735656            0.058388 -276.227692   

           mfcc2       mfcc3       mfcc4  ...     mfcc12     mfcc13  \
0      66.996750    2.773713   -7.344683  ...  -8.083671  -5.048218   
1     189.844299   43.456573  -14.843616  ...  -0.261810  -3.648379   
2     -52.098198  -29.272726   51.450451  ...  -6.393055  -0.816413   
3     111.165787 -118.823204  101.380623  ...  -8.901740  14.788354   
4     111.165787 -118.823204  101.380623  ...  -8.901740  14.788354   
...          ...         ...         ...  ...        ...        ...   
4091   36.750389  -55.689747   73.938583  ...  11.632354  24.769184   
4092   -8.231347  -39.087692   15.918352  ...   2.623544  58.025414   
4093  -28.432560  -57.578430   91.676506  ... -18.044823  11.433823   
4094  104.008972  -26.208755   53.464386  ... -23.727808  -3.421882   
4095   56.102425  -55.731079   48.095951  ... -14.707502  -1.791384   

         mfcc14     mfcc15     mfcc16     mfcc17     mfcc18     mfcc19  \
0     -6.389764  -3.771957  -5.420980  -6.060807  -8.996303  -6.962704   
1     -7.170358  -8.678823  -3.089788   1.779325   1.426942  -0.562221   
2    -21.469234   7.891709  -8.986416  21.074375  -3.472238 -24.394167   
3    -18.563610  19.579359 -19.051245  17.527319 -13.264457   9.172668   
4    -18.563610  19.579359 -19.051245  17.527319 -13.264457   9.172668   
...         ...        ...        ...        ...        ...        ...   
4091 -24.416580  22.626951 -10.902688  18.290472   2.032426 -11.142293   
4092  30.693241  -3.983568  -0.308079  20.071917 -35.369507  -2.600209   
4093 -12.647687   5.235250 -17.038450   1.529860 -11.974364   5.367595   
4094   2.979419  -1.454737  -4.183025  -0.519505  -9.737333   2.976835   
4095  -3.141917   6.261209  -2.807244  -6.140350 -10.702525   0.009002   

         mfcc20          label  
0      1.869202  Bass_Acoustic  
1     -4.903541  Bass_Acoustic  
2     -9.087689  Bass_Acoustic  
3     -4.606864  Bass_Acoustic  
4     -4.606864  Bass_Acoustic  
...         ...            ...  
4091  15.200210    vocal_synth  
4092  68.903610    vocal_synth  
4093  -9.757542    vocal_synth  
4094  -4.131946    vocal_synth  
4095  -4.836519    vocal_synth  

[4096 rows x 27 columns]

In [5]:
data.shape

(4096, 27)

In [6]:
data = data.drop(['filename'],axis=1)

In [7]:
instrument_list = data.iloc[:, -1] #selects the last column as instrument list 

encoder = LabelEncoder()
y = encoder.fit_transform(instrument_list)#encodes the instrument column int o0s to 10s

In [8]:
scaler = StandardScaler()
X = scaler.fit_transform(np.array(data.iloc[:, :-1], dtype = float))

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [10]:
x_val = X_train[:200]
partial_x_train = X_train[200:]

y_val = y_train[:200]
partial_y_train = y_train[200:]


In [11]:
from keras import models
from keras import layers
model = models.Sequential()
model.add(layers.Dense(512, activation='relu', input_shape=(X_train.shape[1],)))
model.add(layers.Dense(256, activation='relu'))
model.add(layers.Dense(128, activation='relu'))
model.add(layers.Dense(64, activation='relu'))
model.add(layers.Dense(15, activation='softmax')) #first parameter is the no of labels.change it accordingly

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(partial_x_train,
          partial_y_train,
          epochs=30,
          batch_size=512,
          validation_data=(x_val, y_val))

Using TensorFlow backend.


Train on 3076 samples, validate on 200 samples
Epoch 1/30
3076/3076 [==============================] - 1s 169us/step - loss: 2.5729 - accuracy: 0.1772 - val_loss: 2.3485 - val_accuracy: 0.2650
Epoch 2/30
3076/3076 [==============================] - 0s 47us/step - loss: 2.2555 - accuracy: 0.2633 - val_loss: 2.0798 - val_accuracy: 0.3800
Epoch 3/30
3076/3076 [==============================] - 0s 39us/step - loss: 2.0342 - accuracy: 0.3674 - val_loss: 1.8782 - val_accuracy: 0.4050
Epoch 4/30
3076/3076 [==============================] - 0s 42us/step - loss: 1.8356 - accuracy: 0.4086 - val_loss: 1.7247 - val_accuracy: 0.4400
Epoch 5/30
3076/3076 [==============================] - 0s 43us/step - loss: 1.6831 - accuracy: 0.4616 - val_loss: 1.6220 - val_accuracy: 0.4650
Epoch 6/30
3076/3076 [==============================] - 0s 41us/step - loss: 1.5332 - accuracy: 0.4935 - val_loss: 1.4579 - val_accuracy: 0.5050
Epoch 7/30
3076/3076 [==============================] - 0s 39us/step - loss: 1.449

In [12]:
#We NEED TO SAVE THE MODEL NOW #and experiment on music data
model.save("instruments-recognition.h5")

In [13]:
predictions = model.predict_classes(X_test)
predictions

array([10,  5, 11,  1,  0,  4, 10,  7,  9,  1, 12,  2,  4,  7,  1, 10,  4,
        1, 11,  7,  0,  1, 10,  5,  7,  7,  2,  9, 10, 10, 11,  3,  1,  1,
        1, 10,  9, 12,  4,  0,  7,  4,  2,  7,  1, 12, 11,  7,  4, 11,  1,
        2,  7, 12, 12, 13,  5,  1,  7,  2, 10,  3,  7, 13,  1,  7,  2,  1,
        7,  1, 11,  1,  7,  4,  1, 10,  7,  1,  9, 12, 11,  4,  7, 10,  7,
        7, 11,  4, 11,  8,  7,  4,  0, 13, 10,  4,  4,  4,  4, 10,  9,  0,
        4, 12, 10, 10,  0,  1,  7,  2,  3,  4,  1, 10,  1,  1,  0,  7,  8,
        4,  1,  9,  7, 10,  9,  4,  0,  0,  1,  9,  9, 10, 13, 10, 10, 12,
        1,  7,  7, 10,  1,  7,  8, 10,  1, 11,  7, 12,  1,  7,  5,  0,  1,
        7,  7,  8,  3,  1, 12, 10,  7,  7, 11,  2,  3, 12,  7, 12,  8,  7,
        7, 11,  4,  7, 11,  0, 10,  7,  2,  1,  1,  4,  1,  0, 10, 12, 10,
        9,  4, 10,  1,  1, 10,  4,  0,  2,  9,  9,  1,  3, 10, 10,  8,  4,
       10, 10,  7,  9,  7,  1,  1,  7,  5,  4,  2,  7,  9, 12,  7, 10,  3,
        0,  9, 10,  1,  1

In [14]:
C=confusion_matrix(y_test, predictions) #PLots the Confusion MAtrix

In [15]:
C

array([[ 45,   0,   0,   1,   0,   0,   0,   0,   0,   0,   0,   0,   4,
          0],
       [  1, 101,   0,   0,   1,   1,   0,  21,   0,   8,   2,   0,   0,
          3],
       [  0,   1,  38,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0],
       [  1,   1,   0,  22,   5,   0,   0,   0,   0,   0,   1,   0,   1,
          1],
       [  1,  11,   0,   0,  40,   8,   1,  22,   2,   7,   3,   0,   0,
          1],
       [  0,   1,   0,   0,   6,  19,   2,   9,   0,   3,   4,   0,   0,
          0],
       [  0,   2,   0,   0,   0,   0,   4,  10,   0,   0,   1,   0,   0,
          0],
       [  1,   5,   0,   0,   4,   4,   0,  83,   0,   0,   2,   0,   0,
          0],
       [  0,   1,   0,   0,   1,   0,   0,   0,  19,   0,   0,   0,   0,
          0],
       [  1,   6,   1,   0,   5,   0,   0,   7,   0,  26,   1,   0,   0,
          0],
       [  0,   1,   0,   4,   1,   1,   0,   2,   0,   0,  81,   2,   0,
          4],
       [  3,   0,   0,   3,   0,   0,   0, 

In [16]:
K=(C / C.astype(np.float).sum(axis=1))*100
K

array([[90.        ,  0.        ,  0.        ,  3.125     ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  6.55737705,  0.        ],
       [ 2.        , 73.1884058 ,  0.        ,  0.        ,  1.04166667,
         2.27272727,  0.        , 21.21212121,  0.        , 17.0212766 ,
         2.08333333,  0.        ,  0.        , 11.53846154],
       [ 0.        ,  0.72463768, 97.43589744,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ],
       [ 2.        ,  0.72463768,  0.        , 68.75      ,  5.20833333,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         1.04166667,  0.        ,  1.63934426,  3.84615385],
       [ 2.        ,  7.97101449,  0.        ,  0.        , 41.66666667,
        18.18181818,  5.88235294, 22.22222222,  9.52380952, 14.89361702,
         3.125     ,  0.  

In [18]:
for i in range (14):
    print(K[i][i])

90.0
73.18840579710145
97.43589743589743
68.75
41.66666666666667
43.18181818181818
23.52941176470588
83.83838383838383
90.47619047619048
55.319148936170215
84.375
87.03703703703704
81.9672131147541
88.46153846153845


predictions[0].shape

In [19]:
np.sum(predictions[0])

10

In [20]:
np.argmax(predictions[0])

0

In [21]:
y_test

array([10,  5, 11,  1,  0,  7, 10,  7,  4,  1, 12,  2,  8,  1,  1,  4,  4,
        1, 11, 12,  0,  1,  1,  7,  9,  1,  2,  5, 10, 10, 11, 11,  1,  1,
        1, 10,  4, 12,  4,  0,  7,  3,  2,  7,  1, 12, 11,  7,  4, 11,  9,
        2,  7, 12, 12, 13,  5,  1,  7,  2, 10, 10,  7,  1,  1,  4,  2,  3,
        5,  4, 11,  1,  7,  4,  1, 10,  7,  4,  9, 12, 11,  5,  9, 10,  4,
        1, 11,  4, 10,  8, 12,  4,  1, 10, 10,  4,  4,  4,  4, 10,  1,  0,
        9, 12, 10, 10,  0,  1,  1,  2,  3,  7,  6, 10,  1,  1,  0,  5,  8,
        3,  1,  1,  4, 10,  1,  4,  0,  0,  1,  1,  9, 10, 13, 10,  5, 12,
        1,  6,  1, 10,  1,  1,  8, 10,  1, 11,  7, 12,  1,  5,  4,  0,  1,
        5, 10,  8,  3,  1, 12, 10,  7,  7, 11,  2,  0,  0,  7,  0,  8,  7,
        7, 11,  4,  7, 11,  0, 10,  7,  2,  1,  1,  4,  1,  7, 10,  0, 10,
        5,  7, 10,  1,  4, 10,  4,  0,  2,  9,  9,  1,  3, 10, 10,  8,  4,
       10,  7,  1,  9,  1,  1,  1,  7,  5,  4,  2,  4,  9, 12,  5, 10,  3,
        0,  4, 10,  1,  1

In [22]:
e=predictions-y_test
e

array([  0,   0,   0,   0,   0,  -3,   0,   0,   5,   0,   0,   0,  -4,
         6,   0,   6,   0,   0,   0,  -5,   0,   0,   9,  -2,  -2,   6,
         0,   4,   0,   0,   0,  -8,   0,   0,   0,   0,   5,   0,   0,
         0,   0,   1,   0,   0,   0,   0,   0,   0,   0,   0,  -8,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,  -7,   0,  12,   0,
         3,   0,  -2,   2,  -3,   0,   0,   0,   0,   0,   0,   0,  -3,
         0,   0,   0,  -1,  -2,   0,   3,   6,   0,   0,   1,   0,  -5,
         0,  -1,   3,   0,   0,   0,   0,   0,   0,   8,   0,  -5,   0,
         0,   0,   0,   0,   6,   0,   0,  -3,  -5,   0,   0,   0,   0,
         2,   0,   1,   0,   8,   3,   0,   8,   0,   0,   0,   0,   8,
         0,   0,   0,   0,   5,   0,   0,   1,   6,   0,   0,   6,   0,
         0,   0,   0,   0,   0,   0,   2,   1,   0,   0,   2,  -3,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   3,  12,   0,  12,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   

In [23]:
exec_data = pd.read_csv('execute.csv') #Fresh Unkonwn data system that doesnt know features extracted from. antoher prgram
exec_data

FileNotFoundError: [Errno 2] File b'execute.csv' does not exist: b'execute.csv'

In [24]:
Yex = exec_data.iloc[:, :1];
Yex =np.array(exec_data.iloc[:, :1])
exec_data

NameError: name 'exec_data' is not defined

In [ ]:
exec_data = exec_data.drop(['filename'],axis=1)
scaler = StandardScaler()
Xex = scaler.fit_transform(np.array(exec_data.iloc[:, :], dtype = float))
predictions = model.predict_classes(Xex)
predictions

In [ ]:
#p=[0]*len(exec_data)
#confusion_matrix(p, predictions) #PLots the Confusion MAtrix

In [ ]:
#Class -0=Piano
#Class -1=Strings
X_train.shape

In [ ]:
K[2][0]

In [ ]:
K[2][1]

In [ ]:
os.getcwd()

In [ ]:
3<<8

In [ ]:
1<<8

In [ ]:
(4<<8)+15