In [9]:
# feature extractoring and preprocessing data
import librosa
import time
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
from PIL import Image
import pathlib 
import IPython
import csv

# Preprocessing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import confusion_matrix

#Import Tensorflow
import tensorflow as tf
#Keras
from tensorflow import keras

import warnings
warnings.filterwarnings('ignore')

os.chdir("/Users/shreevathsapk/Desktop/Miniprj")

In [10]:
data = pd.read_csv('execute.csv')
data.shape
data = data.drop(['filename'],axis=1)

instrument_list = data.iloc[:, -1] #selects the last column as instrument list 

encoder = LabelEncoder()
y = encoder.fit_transform(instrument_list)#encodes the instrument column int o0s and 1s

scaler = StandardScaler()
X = scaler.fit_transform(np.array(data.iloc[:, :-1], dtype = float))

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)


In [11]:
X_train.shape

(349, 24)

In [12]:
from keras import models
from keras import layers

model = models.Sequential()

model.add(layers.Dense(512, activation='relu', input_shape=(25,)))

model.add(layers.Dense(256, activation='relu'))

model.add(layers.Dense(128, activation='relu'))

model.add(layers.Dense(64, activation='relu'))

model.add(layers.Dense(10, activation='softmax'))
#
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])
#
history = model.load_weights("instruments-recognition.h5")

"""
from keras import models
from keras import layers
model = models.Sequential()
model.add(layers.Dense(512, activation='relu', input_shape=(X_train.shape[1],)))
model.add(layers.Dense(256, activation='relu'))
model.add(layers.Dense(128, activation='relu'))
model.add(layers.Dense(64, activation='relu'))
model.add(layers.Dense(10, activation='softmax'))

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(partial_x_train,
          partial_y_train,
          epochs=30,
          batch_size=512,
          validation_data=(x_val, y_val))
"""

"\nfrom keras import models\nfrom keras import layers\nmodel = models.Sequential()\nmodel.add(layers.Dense(512, activation='relu', input_shape=(X_train.shape[1],)))\nmodel.add(layers.Dense(256, activation='relu'))\nmodel.add(layers.Dense(128, activation='relu'))\nmodel.add(layers.Dense(64, activation='relu'))\nmodel.add(layers.Dense(10, activation='softmax'))\n\nmodel.compile(optimizer='adam',\n              loss='sparse_categorical_crossentropy',\n              metrics=['accuracy'])\n\nmodel.fit(partial_x_train,\n          partial_y_train,\n          epochs=30,\n          batch_size=512,\n          validation_data=(x_val, y_val))\n"

In [13]:
exec_data = pd.read_csv('execute.csv')
exec_data.shape
exec_data = exec_data.drop(['filename'],axis=1)
exec_data_list = exec_data.iloc[:,:]
exec_data_list

chroma_stft  spectral_centroid  spectral_bandwidth      rolloff  \
0       0.240382         989.496963         1282.448746  1900.985823   
1       0.133086        1758.981451         1725.830686  2417.972228   
2       0.167430        1146.801064         1428.404519  1831.000963   
3       0.144603         569.300854         1149.135040   760.006714   
4       0.367517        1521.980313         1816.161244  2460.168457   
..           ...                ...                 ...          ...   
457     0.429886        1212.943206         1839.307232  2177.120169   
458     0.189774        1510.054974         1775.956403  2394.017727   
459     0.265123        1124.508752         1499.242751  2000.054573   
460     0.155186        1741.600125         2113.052250  2915.526116   
461     0.174337        1355.192443         2001.174818  2458.745286   

     zero_crossing_rate       mfcc1       mfcc2      mfcc3      mfcc4  \
0              0.048716 -196.939316  174.339005 -23.644669  31.683804   
1              0.105146 -555.918335   29.257957 -41.606461  -9.762589   
2              0.049105 -573.833008   98.944763 -34.956959   3.577116   
3              0.038914 -744.192932  108.768784   6.251323   8.540523   
4              0.074371 -504.225098   22.397329 -17.381876   4.547052   
..                  ...         ...         ...        ...        ...   
457            0.042969 -630.593262   76.419930  -9.104266   9.021695   
458            0.065827 -527.085388   56.065067 -27.394852   1.820737   
459            0.044778 -652.178772   89.658821 -32.387615   2.647335   
460            0.086108 -599.896545   20.604736 -30.715546  -1.426141   
461            0.064470 -135.402664  131.650589  32.174683  23.157568   

         mfcc5  ...     mfcc11     mfcc12     mfcc13     mfcc14     mfcc15  \
0     6.125992  ... -12.652734  -2.454622   0.421472  -9.684428  -8.086060   
1    10.354194  ...   7.396856   7.028731  16.574821  25.886534  18.900482   
2    10.468472  ...  14.068758   1.966460   2.847129  15.640727  12.392844   
3    23.519321  ...   2.760118  -0.593461  -4.014421   4.009748   3.089754   
4    10.489569  ...  20.432928   3.413163  -4.417702   8.618738  18.559750   
..         ...  ...        ...        ...        ...        ...        ...   
457  12.453717  ...  23.367128  19.208939   5.219634  -7.603517  -3.952813   
458  -6.866810  ...  27.752016   7.385140 -13.739231 -18.476929  -5.314015   
459   5.803692  ...  18.676817  25.038385  33.742668  41.155331  15.885791   
460  14.787951  ...  -8.684547  13.789086  42.022549  40.979534  22.165770   
461  -7.713911  ...   5.387659  -0.810036 -15.432736 -10.593287  -6.612549   

        mfcc16     mfcc17     mfcc18     mfcc19     mfcc20  
0     2.749654   0.749361   3.815797   7.294054   5.203331  
1    12.289899  14.799192  12.880098   9.227118   2.732165  
2    14.277587  24.872581  27.413567  25.503277  14.017136  
3    10.567451  32.198288  58.192707  55.229412  36.315224  
4    26.817764  20.850071   5.576908  -9.908314  -0.435067  
..         ...        ...        ...        ...        ...  
457   1.336497   2.435658   7.064709  10.700412  26.464756  
458  14.838204   5.258687  14.536113  38.430420  39.749393  
459  -9.190211  -3.251722  10.177946  10.891975   0.271764  
460   6.524533  -5.578141  -7.881909  15.577080  39.003540  
461   6.050275   4.153692   8.704792   8.558250   7.466763  

[462 rows x 25 columns]

In [14]:
scaler = StandardScaler()
X_ex=np.array(exec_data_list.iloc[:]);
#X_ex = scaler.fit_transform(np.array(exec_data_list.iloc[:,:], dtype = float))
X_ex

array([[ 2.40381703e-01,  9.89496963e+02,  1.28244875e+03, ...,
         3.81579733e+00,  7.29405355e+00,  5.20333147e+00],
       [ 1.33085728e-01,  1.75898145e+03,  1.72583069e+03, ...,
         1.28800983e+01,  9.22711754e+00,  2.73216462e+00],
       [ 1.67430088e-01,  1.14680106e+03,  1.42840452e+03, ...,
         2.74135666e+01,  2.55032768e+01,  1.40171356e+01],
       ...,
       [ 2.65122622e-01,  1.12450875e+03,  1.49924275e+03, ...,
         1.01779461e+01,  1.08919754e+01,  2.71764189e-01],
       [ 1.55185580e-01,  1.74160012e+03,  2.11305225e+03, ...,
        -7.88190937e+00,  1.55770798e+01,  3.90035400e+01],
       [ 1.74337283e-01,  1.35519244e+03,  2.00117482e+03, ...,
         8.70479202e+00,  8.55825043e+00,  7.46676254e+00]])

In [15]:
sample = X_ex
sample

array([[ 2.40381703e-01,  9.89496963e+02,  1.28244875e+03, ...,
         3.81579733e+00,  7.29405355e+00,  5.20333147e+00],
       [ 1.33085728e-01,  1.75898145e+03,  1.72583069e+03, ...,
         1.28800983e+01,  9.22711754e+00,  2.73216462e+00],
       [ 1.67430088e-01,  1.14680106e+03,  1.42840452e+03, ...,
         2.74135666e+01,  2.55032768e+01,  1.40171356e+01],
       ...,
       [ 2.65122622e-01,  1.12450875e+03,  1.49924275e+03, ...,
         1.01779461e+01,  1.08919754e+01,  2.71764189e-01],
       [ 1.55185580e-01,  1.74160012e+03,  2.11305225e+03, ...,
        -7.88190937e+00,  1.55770798e+01,  3.90035400e+01],
       [ 1.74337283e-01,  1.35519244e+03,  2.00117482e+03, ...,
         8.70479202e+00,  8.55825043e+00,  7.46676254e+00]])

In [16]:

#for i in range(len(X_test)):
    
test_img = sample.reshape((len(sample),25))
img_class = model.predict_classes(test_img)
print('audio contains instrument ',img_class)
#img_class[0]
#sample[0]

audio contains instrument  [1 1 1 3 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 3 1 1 1 1 1 1 1 3
 1 1 1 1 1 1 1 1 1 1 1 1 3 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 3 1 1 1 1 3 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 3 3 1 1 1 1 1 1 1 1 1 1 3 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 3 1 1 1 1 1 1 1 3 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 3 1 1 1 1 1 1 1 1 1 1 1 1 1 1 3 1 1 1 1 1 1 1 1 1 1 1 1 3 3 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 3 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 3 1 1 1 1 1 1 1 1 1 1 1 3 1 1 1 1 1 1 3 1 1 1 1 1 1 1 1 3
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 3 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 3 1 1 1 1 3 3 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 3 1 1 1 1 1 1 1 1 1 3 1 1 1 1 1 1 1 1 1 1 1 3 1 1 1 1 1 1 1
 3 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [17]:
X_test

array([[-1.08601269, -1.09949141, -0.98024312, ..., -0.78637884,
        -0.48226605,  0.03574963],
       [-0.20768973, -0.62502776, -0.59261203, ...,  0.17009237,
         0.02655045, -0.1009756 ],
       [ 0.75967087,  0.62538283,  1.58446521, ..., -1.3410357 ,
        -0.7991049 ,  0.11684759],
       ...,
       [ 0.73137827, -0.47147926, -0.14448994, ..., -0.32101708,
         1.52965201,  2.1819175 ],
       [ 1.29545434, -0.10723901,  0.64206969, ..., -0.89141496,
        -1.10707094,  0.0670957 ],
       [ 1.99756693, -0.28180278,  1.58809109, ..., -0.63079004,
        -1.53741643, -0.07654134]])